/*
 * 5G-EIR Equipment Identity Check
 *
 * 5G-EIR Equipment Identity Check Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"
	"net/http"
	// WARNING!
	// Change this to a fully-qualified import path
	// once you place this file into your project.
	// For example,
	//
	//    sw "github.com/myname/myrepo/go"
	//
	sw "./go"
)

func main() {
	log.Printf("Server started")

	sw.RedisConnect()

	router := sw.NewRouter()

	// redis
	// newPool returns a pointer to a redis.Pool
	//pool := sw.RedisNewPool()
	// get a connection from the pool (redis.Conn)
	//conn := pool.Get()
	// use defer to close the connection when the function completes
	//defer conn.Close()

	log.Fatal(http.ListenAndServe(":8080", router))
}
