apiVersion: v1
kind: Service
metadata:
  name: five-g-eir-frontend-loadbalancer
spec:
  selector:
    app: 5g-eir
    tier: frontend
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  type: LoadBalancer

