/*
 * 5G-EIR Equipment Identity Check
 *
 * 5G-EIR Equipment Identity Check Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"encoding/json"
	"fmt"
	"net/http"
	//"github.com/gomodule/redigo/redis"
)

// GetEquipmentStatus - Retrieves the status of the UE
func GetEquipmentStatus(w http.ResponseWriter, r *http.Request) {
	pei := r.FormValue("pei")
	//fmt.Println("pei:", pei)

	//myEquipmentStatus := WHITELISTED
	//err := errors.New("testerror")
	myEquipmentStatus, err := redisQueryEquipmentStatus(pei)
	if err != nil {
		// in case of an error
		fmt.Println(err)
		w.Header().Set("Content-Type", "application/problem+json; charset=UTF-8")
		//w.WriteHeader(http.StatusNotFound)
		w.WriteHeader(http.StatusInternalServerError)
	} else {
		// in case of success
		w.Header().Set("Content-Type", "application/json; charset=UTF-8")
		w.WriteHeader(http.StatusOK)
		myEirResponseData := &EirResponseData{Status: &myEquipmentStatus}
		myEirResponseDataJson, _ := json.Marshal(myEirResponseData)
		//fmt.Println(string(myEirResponseDataJson))
		fmt.Fprintf(w, "%s", myEirResponseDataJson)
	}
}
