/*
 * 5G-EIR Equipment Identity Check
 *
 * 5G-EIR Equipment Identity Check Service
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"fmt"
	"net/http"
	"os"
	"time"
)

func Logger(inner http.Handler, name string) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		start := time.Now()
		hostname, err := os.Hostname()
		if err != nil {
			panic(err)
		}
		inner.ServeHTTP(w, r)

		//log.Printf(
		//	"%s %s %s %s %s",
		//	hostname,
		//	r.Method,
		//	r.RequestURI,
		//	name,
		//	time.Since(start),
		//)

		fmt.Printf(
			"[%s] [%s] %s %s %s %s\n",
			hostname,
			"http",
			r.Method,
			r.RequestURI,
			name,
			time.Since(start),
		)
	})
}

func WriteLog(module string, text string) {
	hostname, err := os.Hostname()
	if err != nil {
		panic(err)
	}

	fmt.Printf(
		"[%s] [%s] %s\n",
		hostname,
		module,
		text,
	)
}
